"""Changed name id column to user_id

Revision ID: e5921d65af2f
Revises: 73380e9a1eea
Create Date: 2024-06-11 10:35:21.098691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5921d65af2f'
down_revision: Union[str, None] = '73380e9a1eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.drop_index('ix_user_id', table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
