"""This is to create Labels model

Revision ID: 559088d55431
Revises: 5d78d356d740
Create Date: 2024-06-12 12:22:58.081481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559088d55431'
down_revision: Union[str, None] = '5d78d356d740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('labels_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('label_name', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('labels_id')
    )
    op.create_index(op.f('ix_labels_labels_id'), 'labels', ['labels_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_labels_id'), table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
