"""This is to create a user model

Revision ID: 7404cad8f72e
Revises: 
Create Date: 2024-06-10 15:49:52.407100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7404cad8f72e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('notes_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('remainder', sa.String(length=50), nullable=True),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.Column('is_trash_bool', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('notes_id')
    )
    op.create_index(op.f('ix_notes_notes_id'), 'notes', ['notes_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_notes_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
