"""This is to create a user model

Revision ID: a0b3bf850c0b
Revises: 7404cad8f72e
Create Date: 2024-06-10 16:24:44.070426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0b3bf850c0b'
down_revision: Union[str, None] = '7404cad8f72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_column('notes', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###
